
(1 "Czy chodzi bokiem?") 
(2 "Czy chowa glowe w piasek?") 
(3 "Czy daje miod?") 
(4 "Czy jest drapiezny?") 
(5 "Czy jest gadem?") 
(6 "Czy jest jajorodny?") 
(7 "Czy jest miesozerny?") 
(8 "Czy jest ptakiem?") 
(9 "Czy jest skorupiakiem?") 
(10 "Czy jest ssakiem?") 
(11 "Czy jest to wymarly gatunek?") 
(12 "Czy ma dluga szyje?") 
(13 "Czy ma kolorowe upierzenie?") 
(14 "Czy ma paski?") 
(15 "Czy ma pletwy?") 
(16 "Czy ma trabe?") 
(17 "Czy ma troje oczu?") 
(18 "Czy mieszka na biegunie?") 
(19 "Czy nosi swój dom na plecach?") 
(20 "Czy pije krew?") 
(21 "Czy razi pradem?") 
(22 "Czy szybko biega?") 
(23 "Czy umie latac?") 
(24 "Czy umie plywac?") 
(25 "Czy wytwarza perly?") 
(26 "Czy zyje na ladzie?") 
(27 "Czy zyje w muszli?") 
(28 "Czy lubi placki?") 